services:
  sovits:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sovits
    environment:
      - is_half=true
      - is_share=true
    volumes:
      - ./output:/workspace/output
      - ./logs:/workspace/logs
      - ./SoVITS_weights:/workspace/SoVITS_weights
      - ./reference:/workspace/reference
      - ./GPT_weights_v2:/workspace/GPT_weights_v2
      - ./SoVITS_weights_v2:/workspace/SoVITS_weights_v2
    working_dir: /workspace
    ports:
      - "5006:5006"
      - "5007:5007"
    shm_size: 16G
    deploy:
      resources:
        limits:
          cpus: '16'
        reservations:
          devices:
          - driver: nvidia
            count: "all"
            capabilities: [gpu]
    stdin_open: true
    tty: true
    restart: unless-stopped
